export const LanguageDemo = {
  python: '',
  less: '',
  scss: '',
  css: '',
  typescript: '',
  javascript: '',
  json: '',
  sql: '',
  markdown: '',
  html: '',
  yaml: '',
  plaintext: '',
  graphql: '',
  abap: '',
  apex: '',
  azcli: '',
  bat: '',
  bicep: '',
  cameligo: '',
  clojure: '',
  coffeescript: '',
  c: '',
  cpp: '',
  csharp: '',
  csp: '',
  cypher: '',
  dart: '',
  dockerfile: '',
  ecl: '',
  elixir: '',
  flow9: '',
  fsharp: '',
  freemarker2: '',
  'freemarker2.tag-angle.interpolation-dollar': '',
  'freemarker2.tag-bracket.interpolation-dollar': '',
  'freemarker2.tag-angle.interpolation-bracket': '',
  'freemarker2.tag-bracket.interpolation-bracket': '',
  'freemarker2.tag-auto.interpolation-dollar': '',
  'freemarker2.tag-auto.interpolation-bracket': '',
  go: '',
  handlebars: '',
  hcl: '',
  ini: '',
  java: '',
  julia: '',
  kotlin: '',
  lexon: '',
  lua: '',
  liquid: '',
  m3: '',
  mips: '',
  msdax: '',
  mysql: '',
  'objective-c': '',
  pascal: '',
  pascaligo: '',
  perl: '',
  pgsql: '',
  php: '',
  pla: '',
  postiats: '',
  powerquery: '',
  powershell: '',
  proto: '',
  pug: '',
  qsharp: '',
  r: '',
  razor: '',
  redis: '',
  redshift: '',
  restructuredtext: '',
  ruby: '',
  rust: '',
  sb: '',
  scala: '',
  scheme: '',
  shell: '',
  sol: '',
  aes: '',
  sparql: '',
  st: '',
  swift: '',
  systemverilog: '',
  verilog: '',
  tcl: '',
  twig: '',
  vb: '',
  xml: '',
};

export const LanguagePrettierParser = {
  json: 'json',
  javascript: 'babel',
  typescript: 'typescript',
  css: 'css',
  less: 'less',
  scss: 'scss',
  markdown: 'markdown',
  graphql: 'graphql',
  handlebars: 'handlebars',
  html: 'html',
  yaml: 'yaml',
};

export const SupportLanguages = [...Object.keys(LanguagePrettierParser), 'rust', 'sql', 'java'];

export const Languages = Object.keys(LanguageDemo);

export enum EMonacoEditorTheme {
  VS = 'vs',
  VSDark = 'vs-dark',
  HCBlack = 'hc-black',
  HCLight = 'hc-light',
}
